name: Builds

on:
  pull_request:
  push:

jobs:
  build:
    name: '${{ matrix.derivation }} on ${{ matrix.operating-system }}'
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
        derivation:
          - php56
          - php70
          - php71
          - php72
          - php73
          - php74
          - php80
          - php81
          - php56-nts
          - php70-nts
          - php71-nts
          - php72-nts
          - php73-nts
          - php74-nts
          - php80-nts
          - php81-nts
          - env-php56
          - env-php70
          - env-php71
          - env-php72
          - env-php73
          - env-php74
          - env-php80
          - env-php81
          - env-php56-nts
          - env-php70-nts
          - env-php71-nts
          - env-php72-nts
          - env-php73-nts
          - env-php74-nts
          - env-php80-nts
          - env-php81-nts

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16

      - uses: cachix/cachix-action@v10
        with:
          name: nix-shell
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build ${{ matrix.derivation }}
        run: |
          nix build .#${{ matrix.derivation }}

