name: Builds

on:
  pull_request:
  push:

jobs:
  build:
    name: '${{ matrix.derivation }} on ${{ matrix.operating-system }}'
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
        derivation:
          - php56
          - php70
          - php71
          - php72
          - php73
          - php74
          - php80
          - php81

    steps:
      - uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16

      - uses: cachix/cachix-action@v10
        with:
          name: nix-shell
          # If you chose API tokens for write access OR if you have a private cache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build PHP
        run: |
          nix build #${{ matrix.derivation }}

      - name: Build PHP NTS
        run: |
          nix build #${{ matrix.derivation }}-nts

      - name: Build PHP environment
        run: |
          nix build #env-${{ matrix.derivation }}

      - name: Build PHP NTS environment
        run: |
          nix build #env-${{ matrix.derivation }}-nts
